import { Landing } from './sections';
export { Landing };
export { Login } from './Login';
export { Register } from './Register';
export { Agents } from './Agents';
export { AiVoiceAgent } from './AiVoiceAgent';
export { AiChatbot } from './AiChatbot';
export { AiPhoneAnswering } from './AiPhoneAnswering';
export { AppointmentBooking } from './AppointmentBooking';
export { CustomerSupportPublic } from './CustomerSupportPublic';
export { RealEstateIndustry } from './RealEstateIndustry';
export { HealthcareIndustry } from './HealthcareIndustry';
export { CaseStudies } from './CaseStudies';
export { Pricing } from './Pricing';
export { VoiceAssistancePricing } from './VoiceAssistancePricing';
export { AiChatbotPricing } from './AiChatbotPricing';
export { News } from './News';