import { Landing } from './sections';
export { Landing };
export { Login } from './Login';
export { Register } from './Register';
export { Agents } from './Agents';
export { CaseStudies } from './CaseStudies';
export { Pricing } from './Pricing';
export { VoiceAssistancePricing } from './VoiceAssistancePricing';
export { AiChatbotPricing } from './AiChatbotPricing';
export { News } from './News';